# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Seismic Hazard and Risk Analysis
author: "<a href='https://www.jackwbaker.com'>Jack Baker</a>"
copyright: "2025"
logo: logo.png
  extra_footer: "Licensed under <a href='https://github.com/bakerjw/shra-jupyter?tab=GPL-3.0-1-ov-file#readme'>GPL-3.0 license </a>.<br /><a href='https://github.com/bakerjw/shra-jupyter/issues'>Report issue</a>."


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/bakerjw/bakerjw.github.io
  path_to_book: seismic-hazard-and-risk  # This specifies the subdirectory
  branch: main  # Which branch of the repository should be used when creating links (optional)
  #repository_provider: custom

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com/"
